# Generated by Django 5.2 on 2025-05-06 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_user_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nombre_completo',
        ),
    ]
