# Generated by Django 5.2 on 2025-05-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_user_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('empleado', 'Empleado'), ('empleador', 'Empleador'), ('contador', 'Contador'), ('asesor_legal', 'Asesor Legal'), ('entidad_gubernamental', 'Entidad Gubernamental')], default='empleado', max_length=30),
        ),
    ]
