# Generated by Django 5.2.7 on 2025-10-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='tipo',
            field=models.CharField(choices=[('Actualización de información personal', 'Actualización de información personal'), ('Agregar información', 'Agregar información')], max_length=50),
        ),
    ]
