# Generated by Django 5.2 on 2025-05-03 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Contract', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eps', models.DecimalField(decimal_places=2, max_digits=10)),
                ('arl', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pension', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cesantias', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Contributions', to='Contract.contract')),
            ],
        ),
    ]
