# Generated by Django 5.2 on 2025-05-13 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contribution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='salario_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
