# Generated by Django 5.2 on 2025-05-09 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contract', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='Estado',
            field=models.CharField(default='activo', max_length=20),
        ),
    ]
