# Generated by Django 5.2 on 2025-05-10 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contract', '0003_contract_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='Estado',
            new_name='estado',
        ),
        migrations.AlterField(
            model_name='contract',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
