# Generated by Django 5.2.7 on 2025-10-07 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contract', '0005_contract_empleador_alter_contract_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='fecha_fin',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
